package com.mineguard.platform.shared.infrastructure.mail;

public interface IEmailService {

    /**
     * Sends an onboarding email with login credentials.
     *
     * @param toEmail           recipient address
     * @param role              role enum name (e.g. ROLE_SUPERVISOR)
     * @param generatedUsername the professional identifier generated by UsernameGenerator
     * @param recipientName     full name or company name for the greeting
     * @param temporaryPassword plain-text temporary password (not yet hashed)
     */
    void sendCredentialsEmail(String toEmail, String role, String generatedUsername,
                              String recipientName, String temporaryPassword);

    void sendPasswordResetEmail(String toEmail, String temporaryPassword);
}